api/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'v1/', include('api.v1.urls', namespace='v1'))
]

sih17/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from sih17.views import PredictionsView, LoginView, logout, SignupView, demographics, pipeline, education, team, login

urlpatterns = [
                  url(r'^admin/', admin.site.urls),
                  url(r'api/', include('api.urls', namespace='api')),
                  url(r'^predictions/$', PredictionsView.as_view(), name='predictions'),
                  url(r'^$', login, name='login'),
                  url(r'^logout/$', logout, name='logout'),
                  url(r'^demographics/$', demographics, name='demographics'),
                  url(r'^about_us/$', pipeline, name='pipeline'),
                  url(r'^education/$', education, name='education'),
                  url(r'^team/$', team, name='team')
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

analysis/models.py
import datetime
import os

import magic
from django.core.exceptions import ValidationError
from django.db import models


# Create your models here.
def change_test_file_name(instance, filename):
    extension = filename.split('.')[-1]
    filename = '%s.%s' % (int(datetime.datetime.now().strftime("%s")) * 1000, extension)
    path = 'file-uploads/tests/'
    return os.path.join(path, filename)


def change_predicted_file_name(instance, filename):
    extension = filename.split('.')[-1]
    filename = '%s.%s' % (int(datetime.datetime.now().strftime("%s")) * 1000, extension)
    path = 'file-uploads/prediction/'
    return os.path.join(path, filename)


class AnalysisTest(models.Model):
    test_file = models.FileField(upload_to=change_test_file_name, verbose_name='Analysis file')
    predicted_file = models.FileField(upload_to=change_predicted_file_name, verbose_name='Analysis predicted file')

    def __str__(self):
        return os.path.basename(self.test_file.name)

    def clean(self):
        if self.test_file:
            mime = magic.from_buffer(self.test_file.read(), mime=True)
            if mime != 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':
                raise ValidationError('Invalid file format')

templates/auth_base.html
{% load static %}
{% load cache %}
{% autoescape on %}
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8"/>
        <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <meta name="theme-color" content="#21A567">
        <meta name="mobile-web-app-capable" content="yes"/>
        <meta name="apple-mobile-web-app-capable" content="yes"/>
        <title>
            {% block title %}
            {% endblock %}
        </title>
        <!-- CSS -->
        <link rel="stylesheet" type="text/css"
              href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
        <link href="{% static 'css/reset.css' %}" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
              integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7"
              crossorigin="anonymous">
        <link href="{% static 'css/authentication/authentication.css' %}" rel="stylesheet" type="text/css">
        {% block css %}
        {% endblock %}
        <!-- CSS END -->
    </head>
    <body>
    {% block body %}
    {% endblock %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
            integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS"
            crossorigin="anonymous"></script>
    <!-- JS START -->
    {% block  js %}
    {% endblock %}
    <!-- JS END -->
    {% block endbody_scripts %}
    {% endblock %}
    </body>
    </html>
{% endautoescape %}

templates/employment.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Employment</title>
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,600,600i,700" rel="stylesheet">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"
            integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
    <!-- Preloader -->

</head>
<body>
<!-- Preloader -->
<div id="preloader">
    <div id="status">&nbsp;</div>
</div>
<div id="wrapper">
    <div class="overlay"></div>

    <!-- Sidebar -->
    <nav class="navbar navbar-inverse navbar-fixed-top" id="sidebar-wrapper" role="navigation">
        <ul class="nav sidebar-nav">
            <li class="sidebar-brand">
                <a href="{% url 'login' %}">
                    <img src="{% static 'images/logo/half.png' %}" class="brand-logo">
                </a>
            </li>
            <li>
                <a href="{% url 'login' %}"><i class="fa fa-tachometer" aria-hidden="true"></i>HOME</a>
            </li>
            <li class="active">
                <a href="{% url 'predictions' %}"><i class="fa fa-briefcase" aria-hidden="true"></i>EMPLOYMENT</a>
            </li>
            <li>
                <a href="{% url 'education' %}"><i class="fa fa-graduation-cap" aria-hidden="true"></i>EDUCATION</a>
            </li>
            <li>
                <a href="{% url 'demographics' %}"><i class="fa fa-globe" aria-hidden="true"></i>DEMOGRAPHICS</a>
            </li>
            <!--
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Works <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li class="dropdown-header">Dropdown heading</li>
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
            -->
            <li>
                <a href="{% url 'pipeline' %}"><i class="fa fa-line-chart" aria-hidden="true"></i>ML PIPELINE</a>
            </li>
            <li>
                <a href="{% url 'team' %}"><i class="fa fa-users" aria-hidden="true"></i>ABOUT US</a>
            </li>
        </ul>
    </nav>
    <!-- /#sidebar-wrapper -->

    <!-- Page Content -->
    <div id="page-content-wrapper">
        <button type="button" class="hamburger is-closed" data-toggle="offcanvas">
            <img src="{% static 'images/logo/logo-2x.png' %}" class="small-logo">
        </button>
        <div>
            <div class="page-start">
             <!--   <span class="logout-btn"><a href="{% url 'logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i>Logout</a></span> -->
            </div>

            <div class="dash-top">
                <h4 class="dash-heading">Understanding High Skilled Labour Market in India</h4>
            </div>

         <!--   <div class="file-area animated fadeIn">
                <div class="to-hide">
                    <h2 class="file-head">Upload your file for prediction (*.xls or .xlsx)</h2>
                </div>
                <form action="#" id="predict-form">
                    {% csrf_token %}
                    <div class="to-hide">
                        <input id="id_test_file" name="test_file" type="file" required="">
                        <input type="submit" value="Submit" class="ul-submit">
                        <img src="{% static 'images/load.gif' %}" class="load-icon hidden">
                        <span class="ul-fail hidden animated fadeIn">
                            <span class="fail-text">Upload Failed</span>
                            <i class="fa fa-times fail-icon" aria-hidden="true"></i>
                        </span>
                    </div>
                    <span class="hidden ul-success animated fadeIn">
  						<span class="success-text">Upload Complete. An email with the results will be sent to {{ request.user.email }}</span>
  						<i class="fa fa-check success-icon" aria-hidden="true"></i>
  					</span>
                </form>
                <div class="to-hide guide-text-div">
                        <a href="https://s3-ap-southeast-1.amazonaws.com/sih17/extrapolate/files/Guidelines+(1).pdf" class="guide-text"><i class="fa fa-keyboard-o" aria-hidden="true"></i>
Guidelines for the Input</a>
                        <a href="https://s3-ap-southeast-1.amazonaws.com/sih17/extrapolate/files/template.xlsx" class="guide-text"><i class="fa fa-file-excel-o" aria-hidden="true"></i>
Template Format</a>
                </div>
            </div> -->
            <div class="dash-area">
                <div class="row">
                    <div class="dash-element col-sm-offset-1 col-sm-10 animated fadeInUp">
                        <iframe id="igraph" scrolling="no" style="border:none;" seamless="seamless"
                                src="https://plot.ly/~raunaq/7.embed?link=false" height="425" width="100%"></iframe>
                    </div>
                    <div class="dash-desc-center col-sm-offset-3 col-sm-6 animated fadeInUp">
                        <p class="dash-desc-p">Approved intake is roughly two times the actual intake, across all
                            categories.</p>
                    </div>
                </div>
                <div class="row last-rw">
                    <div class="dash-element col-sm-offset-2 col-sm-4 aml">
                        <iframe id="igraph" scrolling="no" style="border:none;" seamless="seamless"
                                src="https://plot.ly/~raunaq/0.embed?link=false" height="425" width="100%"></iframe>
                    </div>
                    <div class="col-sm-offset-1 col-sm-5 dash-desc amr">
                        <p class="dash-desc-p">The dataset contained a field of College Tier where aptitude score
                            annotated each college with a score of 1 and 2. The annotations have been computed from the
                            average scores obtained by the students in the college/university as well as the institute's
                            reputation. Colleges with an average score above a threshold are tagged as 1 and others as
                            2. College City Tier is annotated based on the population of the city in which the college
                            is located.<br><br>In our observation,<span class="p-bold"> Tier 1 college candidates have secured more salary on an average than Tier 2 college,</span>
                            which coincides with the general trend, whereas the <span class=”p-bold”>college city tier does not affect salary greatly.</span>
                        </p>
                    </div>
                </div>
                <hr>
                <div class="footer">
                    <span class="footer-content">
                        &copy; 2018 AICTE 
                        <img class="footer-img-1" src="{% static 'images/logo/logo-2x.png' %}">
                    </span>
                </div>
            </div>
        </div>
    </div>
    <!-- /#page-content-wrapper -->

</div>

<!-- /#wrapper -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>

<script type="text/javascript" src="{% static 'predictions/predajax.js' %}"></script>
<script type="text/javascript" src="{% static 'js/animate.js' %}"></script>
<script type="text/javascript">
    function init() {
        $('#status').fadeOut(); // will first fade out the loading animation 
        $('#preloader').delay(350).fadeOut('slow'); // will fade out the white DIV that covers the website.
        $('body').delay(350).css({'overflow': 'visible'});

        var a = $(".hamburger"), c = $(".overlay"), b = !1;
        a.click(function () {
            1 == b ? (c.hide(), a.removeClass("is-open"), a.addClass("is-closed"), b = !1) : (c.show(), a.removeClass("is-closed"), a.addClass("is-open"), b = !0);
        });
        window.scrollTo(0, 0);
        animateControl.init();

        $('[data-toggle="offcanvas"]').click(function () {
            $("#wrapper").toggleClass("toggled");
        });
        post_file.init();
    }
    ;
    window.addEventListener('load', init);
</script>
</body>
</html>

templates/team.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Team</title>
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,600,600i,700" rel="stylesheet">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"
            integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/team.css' %}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
    <!-- Preloader -->

</head>
<body>
<!-- Preloader -->
<div id="preloader">
    <div id="status">&nbsp;</div>
</div>
<div id="wrapper">
    <div class="overlay"></div>

    <!-- Sidebar -->
    <nav class="navbar navbar-inverse navbar-fixed-top" id="sidebar-wrapper" role="navigation">
        <ul class="nav sidebar-nav">
            <li class="sidebar-brand">
                <a href="{% url 'login' %}">
                    <img src="{% static 'images/logo/half.png' %}" class="brand-logo">
                </a>
            </li>
            <li>
                <a href="{% url 'login' %}"><i class="fa fa-tachometer" aria-hidden="true"></i>HOME</a>
            </li>
            <li class="active">
                <a href="{% url 'predictions' %}"><i class="fa fa-briefcase" aria-hidden="true"></i>EMPLOYMENT</a>
            </li>
            <li>
                <a href="{% url 'education' %}"><i class="fa fa-graduation-cap" aria-hidden="true"></i>EDUCATION</a>
            </li>
            <li>
                <a href="{% url 'demographics' %}"><i class="fa fa-globe" aria-hidden="true"></i>DEMOGRAPHICS</a>
            </li>
            <!--
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Works <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li class="dropdown-header">Dropdown heading</li>
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
            -->
            <li>
                <a href="{% url 'pipeline' %}"><i class="fa fa-line-chart" aria-hidden="true"></i>ML PIPELINE</a>
            </li>
            <li>
                <a href="{% url 'team' %}"><i class="fa fa-users" aria-hidden="true"></i>ABOUT US</a>
            </li>
        </ul>
    </nav>
    <!-- /#sidebar-wrapper -->

    <!-- Page Content -->
    <div id="page-content-wrapper">
        <button type="button" class="hamburger is-closed" data-toggle="offcanvas">
            <img src="{% static 'images/logo/logo-2x.png' %}" class="small-logo">
        </button>
        <div>
            <div class="page-start">
             <!--   <span class="logout-btn"><a href="{% url 'logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i>Logout</a></span> -->
            </div>

            <div class="dash-top">
                <h4 class="dash-heading">Meet the Team</h4>
            </div>

         <!--   <div class="file-area animated fadeIn">
                <div class="to-hide">
                    <h2 class="file-head">Upload your file for prediction (*.xls or .xlsx)</h2>
                </div>
                <form action="#" id="predict-form">
                    {% csrf_token %}
                    <div class="to-hide">
                        <input id="id_test_file" name="test_file" type="file" required="">
                        <input type="submit" value="Submit" class="ul-submit">
                        <img src="{% static 'images/load.gif' %}" class="load-icon hidden">
                        <span class="ul-fail hidden animated fadeIn">
                            <span class="fail-text">Upload Failed</span>
                            <i class="fa fa-times fail-icon" aria-hidden="true"></i>
                        </span>
                    </div>
                    <span class="hidden ul-success animated fadeIn">
  						<span class="success-text">Upload Complete. An email with the results will be sent to {{ request.user.email }}</span>
  						<i class="fa fa-check success-icon" aria-hidden="true"></i>
  					</span>
                </form>
                <div class="to-hide guide-text-div">
                        <a href="https://s3-ap-southeast-1.amazonaws.com/sih17/extrapolate/files/Guidelines+(1).pdf" class="guide-text"><i class="fa fa-keyboard-o" aria-hidden="true"></i>
Guidelines for the Input</a>
                        <a href="https://s3-ap-southeast-1.amazonaws.com/sih17/extrapolate/files/template.xlsx" class="guide-text"><i class="fa fa-file-excel-o" aria-hidden="true"></i>
Template Format</a>
                </div>
            </div> -->
            <div class="dash-area">
                <div class="row-cards">
                  <div class="column">
                  </div>
                  <div class="column">
                    <div class="card animated bounceInUp">
                      <img class="profile-img" src="{% static 'images/ss.jpg' %}" alt="Jane">
                      <div class="container">
                        <h2 class="name">Dr. N.H. Siddalingaswamy</h2>
                        <p class="title">Mentor &amp; Director (e-Gov & CMAT- GPAT)</p>
                        <p>Some text that describes me lorem ipsum ipsum lorem.</p>
                      </div>
                    </div>
                  </div>
                  <div class="column">
                  </div>
                </div>
                <div class="row-cards">  
                  <div class="column">
                    <div class="card animated bounceInUp">
                      <img class="profile-img" src="{% static 'images/aviral.jpg' %}" alt="Jane">
                      <div class="container">
                        <h2>Jane Doe</h2>
                        <p class="title">CEO &amp; Founder</p>
                        <p>Some text that describes me lorem ipsum ipsum lorem.</p>
                      </div>
                    </div>
                  </div>

                  <div class="column">
                    <div class="card animated bounceInUp">
                      <img class="profile-img" src="{% static 'images/aviral.jpg' %}" alt="Jane">
                      <div class="container">
                        <h2>Jane Doe</h2>
                        <p class="title">CEO &amp; Founder</p>
                        <p>Some text that describes me lorem ipsum ipsum lorem.</p>
                      </div>
                    </div>
                  </div>

                  <div class="column">
                    <div class="card animated bounceInUp">
                      <img class="profile-img" src="{% static 'images/aviral.jpg' %}" alt="Jane">
                      <div class="container">
                        <h2>Jane Doe</h2>
                        <p class="title">CEO &amp; Founder</p>
                        <p>Some text that describes me lorem ipsum ipsum lorem.</p>
                      </div>
                    </div>
                  </div>
                </div>

                <div class="row-cards">  
                  <div class="column">
                    <div class="card animated bounceInUp">
                      <img class="profile-img" src="{% static 'images/aviral.jpg' %}" alt="Jane">
                      <div class="container">
                        <h2>Jane Doe</h2>
                        <p class="title">CEO &amp; Founder</p>
                        <p>Some text that describes me lorem ipsum ipsum lorem.</p>
                      </div>
                    </div>
                  </div>

                  <div class="column">
                    <div class="card animated bounceInUp">
                      <img class="profile-img" src="{% static 'images/aviral.jpg' %}" alt="Jane">
                      <div class="container">
                        <h2>Jane Doe</h2>
                        <p class="title">CEO &amp; Founder</p>
                        <p>Some text that describes me lorem ipsum ipsum lorem.</p>
                      </div>
                    </div>
                  </div>

                  <div class="column">
                    <div class="card animated bounceInUp">
                      <img class="profile-img" src="{% static 'images/aviral.jpg' %}" alt="Jane">
                      <div class="container">
                        <h2>Jane Doe</h2>
                        <p class="title">CEO &amp; Founder</p>
                        <p>Some text that describes me lorem ipsum ipsum lorem.</p>
                      </div>
                    </div>
                  </div>
                </div>

                <hr>
                <div class="footer">
                    <span class="footer-content">
                        &copy; 2018 AICTE 
                        <img class="footer-img-1" src="{% static 'images/logo/logo-2x.png' %}">
                    </span>
                </div>
            </div>
        </div>
    </div>
    <!-- /#page-content-wrapper -->

</div>

<!-- /#wrapper -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>

<script type="text/javascript" src="{% static 'predictions/predajax.js' %}"></script>
<script type="text/javascript" src="{% static 'js/animate.js' %}"></script>
<script type="text/javascript">
    function init() {
        $('#status').fadeOut(); // will first fade out the loading animation 
        $('#preloader').delay(350).fadeOut('slow'); // will fade out the white DIV that covers the website.
        $('body').delay(350).css({'overflow': 'visible'});

        var a = $(".hamburger"), c = $(".overlay"), b = !1;
        a.click(function () {
            1 == b ? (c.hide(), a.removeClass("is-open"), a.addClass("is-closed"), b = !1) : (c.show(), a.removeClass("is-closed"), a.addClass("is-open"), b = !0);
        });
        window.scrollTo(0, 0);
        animateControl.init();

        $('[data-toggle="offcanvas"]').click(function () {
            $("#wrapper").toggleClass("toggled");
        });
        post_file.init();
    }
    ;
    window.addEventListener('load', init);
</script>
</body>
</html>